# Site settings
title: Scalingo Changelog
email: hello@scalingo.com
description: You will find here all the changes on the Scalingo platform.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://changelog.scalingo.com" # the base hostname & protocol for your site
twitter_username: ScalingoHQ
github_username:  Scalingo

# Build settings
markdown: kramdown
